### ISSUE TITLE
Failed to run dqn example

### ISSUE THREAD

**Issue by xdzhang-xdu** [carla-simulator/rllib-integration#28]
My environment is 2080 ti GPU, i9 CPU, 64G Rom, NVIDIA-SMI 470.161.03,   Driver Version: 470.161.03,   CUDA Version: 11.4.

After starting CARLA 0.9.11, I run "python3 dqn_train.py dqn_example/dqn_config.yaml --name dqn" and get the issues as following:

```
(pid=raylet) Traceback (most recent call last):
(pid=raylet)   File "/home/xdzhang/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 21, in <module>
(pid=raylet)     import ray.new_dashboard.utils as dashboard_utils
(pid=raylet)   File "/home/xdzhang/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py", line 25, in <module>
(pid=raylet)     from aiohttp.frozenlist import FrozenList
(pid=raylet) ModuleNotFoundError: No module named 'aiohttp.frozenlist'
....
2023-03-08 12:03:21,910	ERROR trial_runner.py:607 -- Trial DQN_CarlaEnv_126bd_00000: Error processing event.
Traceback (most recent call last):
  File "/home/xdzhang/.local/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 519, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/xdzhang/.local/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 497, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/xdzhang/.local/lib/python3.8/site-packages/ray/worker.py", line 1379, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(IndexError): ray::CustomDQNTrainer.train() (pid=169367, ip=10.27.32.124)
  File "python/ray/_raylet.pyx", line 422, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 456, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 459, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 415, in ray._raylet.execute_task.function_executor
  File "/home/xdzhang/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 106, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/xdzhang/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 465, in __init__
    super().__init__(config, logger_creator)
  File "/home/xdzhang/.local/lib/python3.8/site-packages/ray/tune/trainable.py", line 96, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/xdzhang/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 629, in setup
    self._init(self.config, self.env_creator)
  File "/home/xdzhang/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 133, in _init
    self.workers = self._make_workers(
  File "/home/xdzhang/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 700, in _make_workers
    return WorkerSet(
  File "/home/xdzhang/.local/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 79, in __init__
    remote_spaces = ray.get(self.remote_workers(
ray.exceptions.RayTaskError(IndexError): ray::RolloutWorker.foreach_policy() (pid=169366, ip=10.27.32.124)
  File "python/ray/_raylet.pyx", line 422, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 456, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 459, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 415, in ray._raylet.execute_task.function_executor
  File "/home/xdzhang/.local/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 372, in __init__
    self.env = _validate_env(env_creator(env_context))
  File "/home/xdzhang/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1193, in <lambda>
    register_env(name, lambda config: env_object(config))
  File "/home/xdzhang/rllib-integration/rllib_integration/carla_env.py", line 33, in __init__
    self.reset()
  File "/home/xdzhang/rllib-integration/rllib_integration/carla_env.py", line 37, in reset
    self.hero = self.core.reset_hero(self.experiment.config["hero"])
  File "/home/xdzhang/rllib-integration/rllib_integration/carla_core.py", line 202, in reset_hero
    self.hero_blueprints = self.world.get_blueprint_library().find(hero_config['blueprint'])
IndexError: blueprint 'vehicle.lincoln.mkz_2017' not found
Result for DQN_CarlaEnv_126bd_00000:
  {}
```
could you give me some help?
Thanks.

**Comment by SaiLalithPolawar** [comment]
Hello, Even I am not able to run the dqn_train.py. After a lot of changes in the version of the required libraries and I request you to install packages with following version numbers,
/Package                  Version
------------------------ ----------
absl-py                  1.4.0
aiodns                   3.0.0
aiohttp                  3.7.0
aiohttp-cors             0.7.0
aioredis                 1.3.1
aiosignal                1.3.1
ale-py                   0.8.1
ansicon                  1.89.0
anyio                    3.6.2
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
async-timeout            3.0.0
asynctest                0.13.0
atari-py                 0.2.9
attrs                    23.1.0
backcall                 0.2.0
bcrypt                   4.0.1
beautifulsoup4           4.12.2
bleach                   6.0.0
blessed                  1.20.0
boto3                    1.17.9
botocore                 1.20.112
Brotli                   1.0.9
build                    0.10.0
cachetools               4.2.4
carla                    0.9.12
cchardet                 2.1.7
certifi                  2022.12.7
cffi                     1.15.1
chardet                  3.0.4
charset-normalizer       3.1.0
click                    8.1.3
cloudpickle              2.2.1
colorama                 0.4.6
colorful                 0.5.5
cryptography             40.0.2
debugpy                  1.6.7
decorator                5.1.1
defusedxml               0.7.1
distlib                  0.3.6
dm-tree                  0.1.8
entrypoints              0.4
fastjsonschema           2.16.3
filelock                 3.12.0
frozenlist               1.3.3
google-api-core          2.10.2
google-auth              1.35.0
google-auth-oauthlib     0.4.6
googleapis-common-protos 1.59.0
gpustat                  1.1
grpcio                   1.54.0
gym                      0.26.2
gym-notices              0.0.8
Gymnasium                0.26.3
gymnasium-notices        0.0.1
hiredis                  2.2.2
idna                     3.4
imageio                  2.27.0
importlib-metadata       6.6.0
importlib-resources      5.12.0
ipykernel                6.16.2
ipython                  7.34.0
ipython-genutils         0.2.0
ipywidgets               8.0.6
jedi                     0.18.2
Jinja2                   3.1.2
jinxed                   1.2.0
jmespath                 0.10.0
jsonschema               4.17.3
jupyter                  1.0.0
jupyter_client           7.4.9
jupyter-console          6.6.3
jupyter_core             4.12.0
jupyter-server           1.24.0
jupyterlab-pygments      0.2.2
jupyterlab-widgets       3.0.7
lz4                      4.3.2
Markdown                 3.4.3
markdown-it-py           2.2.0
MarkupSafe               2.1.2
matplotlib-inline        0.1.6
mdurl                    0.1.2
mistune                  2.0.5
msgpack                  1.0.5
multidict                4.7.6
nbclassic                0.5.5
nbclient                 0.7.3
nbconvert                7.3.1
nbformat                 5.8.0
nest-asyncio             1.5.6
networkx                 2.6.3
notebook                 6.5.4
notebook_shim            0.2.2
numpy                    1.21.6
nvidia-ml-py             11.525.112
oauthlib                 3.2.2
opencensus               0.11.2
opencensus-context       0.1.3
opencv-python            4.7.0.72
opencv-python-headless   4.2.0.34
packaging                23.1
pandas                   1.3.5
pandocfilters            1.5.0
paramiko                 2.7.2
parso                    0.8.3
pickleshare              0.7.5
Pillow                   9.5.0
pip                      22.3.1
pip-tools                6.13.0
pkgutil_resolve_name     1.3.10
platformdirs             3.2.0
prometheus-client        0.16.0
prompt-toolkit           3.0.38
protobuf                 3.20.3
psutil                   5.9.5
py-spy                   0.3.14
pyasn1                   0.5.0
pyasn1-modules           0.3.0
pycares                  4.3.0
pycparser                2.21
pygame                   2.0.1
Pygments                 2.15.1
PyNaCl                   1.5.0
pyproject_hooks          1.0.0
pyrsistent               0.19.3
python-dateutil          2.8.2
pytz                     2023.3
PyWavelets               1.3.0
pywin32                  306
pywinpty                 2.0.10
PyYAML                   5.4.1
pyzmq                    25.0.2
qtconsole                5.4.2
QtPy                     2.3.1
ray                      1.1.0
redis                    3.5.0
requests                 2.28.2
requests-oauthlib        1.3.1
rich                     13.3.4
rsa                      4.9
s3transfer               0.3.7
scikit-image             0.19.3
scipy                    1.7.3
scp                      0.13.3
Send2Trash               1.8.0
setuptools               65.6.3
six                      1.16.0
sniffio                  1.3.0
soupsieve                2.4.1
tabulate                 0.9.0
tensorboard              2.4.1
tensorboard-data-server  0.6.1
tensorboard-plugin-wit   1.8.1
tensorboardX             2.6
terminado                0.17.1
tifffile                 2021.11.2
tinycss2                 1.2.1
tomli                    2.0.1
torch                    1.13.1
torchaudio               0.13.1
torchvision              0.14.1
tornado                  6.2
traitlets                5.9.0
typer                    0.7.0
typing_extensions        4.5.0
urllib3                  1.26.15
virtualenv               20.22.0
wcwidth                  0.2.6
webencodings             0.5.1
websocket-client         1.5.1
Werkzeug                 2.2.3
wheel                    0.38.4
widgetsnbextension       4.0.7
wincertstore             0.2
yarl                     1.9.1
zipp                     3.15.0

and was able to run but still facing with the following error,

>  2023-04-24 16:44:06,542      INFO trainer.py:618 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
2023-04-24 16:44:10,071 ERROR trial_runner.py:607 -- Trial DQN_CarlaEnv_7451f_00000: Error processing event.
Traceback (most recent call last):
  File "D:\Softwares\Anaconda\anaconda3\envs\caRl\lib\site-packages\ray\tune\trial_runner.py", line 519, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "D:\Softwares\Anaconda\anaconda3\envs\caRl\lib\site-packages\ray\tune\ray_trial_executor.py", line 497, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "D:\Softwares\Anaconda\anaconda3\envs\caRl\lib\site-packages\ray\worker.py", line 1379, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(KeyError): ray::CustomDQNTrainer.train() (pid=8596, ip=10.0.0.2)        
  File "python\ray\_raylet.pyx", line 422, in ray._raylet.execute_task
  File "D:\Softwares\Anaconda\anaconda3\envs\caRl\lib\site-packages\ray\worker.py", line 171, in reraise_actor_init_error
    raise self.actor_init_error
  File "python\ray\_raylet.pyx", line 456, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 459, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 415, in ray._raylet.execute_task.function_executor
  File "D:\Softwares\Anaconda\anaconda3\envs\caRl\lib\site-packages\ray\function_manager.py", line 556, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "D:\Softwares\Anaconda\anaconda3\envs\caRl\lib\site-packages\ray\rllib\agents\trainer_template.py", line 106, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "D:\Softwares\Anaconda\anaconda3\envs\caRl\lib\site-packages\ray\rllib\agents\trainer.py", line 465, in __init__
    super().__init__(config, logger_creator)
  File "D:\Softwares\Anaconda\anaconda3\envs\caRl\lib\site-packages\ray\tune\trainable.py", line 96, in __init__
    self.setup(copy.deepcopy(self.config))
  File "D:\Softwares\Anaconda\anaconda3\envs\caRl\lib\site-packages\ray\rllib\agents\trainer.py", line 629, in setup
    self._init(self.config, self.env_creator)
  File "D:\Softwares\Anaconda\anaconda3\envs\caRl\lib\site-packages\ray\rllib\agents\trainer_template.py", line 138, in _init
    num_workers=self.config["num_workers"])
  File "D:\Softwares\Anaconda\anaconda3\envs\caRl\lib\site-packages\ray\rllib\agents\trainer.py", line 706, in _make_workers
    logdir=self.logdir)
  File "D:\Softwares\Anaconda\anaconda3\envs\caRl\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 81, in __init__
    lambda p, pid: (pid, p.observation_space, p.action_space)))
  File "D:\Softwares\Anaconda\anaconda3\envs\caRl\lib\site-packages\ray\worker.py", line 1379, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(KeyError): ray::RolloutWorker.foreach_policy() (pid=2140, ip=10.0.0.2)  
  File "python\ray\_raylet.pyx", line 422, in ray._raylet.execute_task
  File "D:\Softwares\Anaconda\anaconda3\envs\caRl\lib\site-packages\ray\worker.py", line 171, in reraise_actor_init_error
    raise self.actor_init_error
  File "python\ray\_raylet.pyx", line 456, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 459, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 415, in ray._raylet.execute_task.function_executor
  File "D:\Softwares\Anaconda\anaconda3\envs\caRl\lib\site-packages\ray\function_manager.py", line 556, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "D:\Softwares\Anaconda\anaconda3\envs\caRl\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 372, in __init__
    self.env = _validate_env(env_creator(env_context))
  File "D:\Softwares\Anaconda\anaconda3\envs\caRl\lib\site-packages\ray\rllib\agents\trainer.py", line 1193, in <lambda>
    register_env(name, lambda config: env_object(config))
  File "D:\Projects\CARLA-RLlib\rllib-integration\rllib_integration\carla_env.py", line 30, in __init__
    self.core = CarlaCore(self.config['carla'])
  File "D:\Projects\CARLA-RLlib\rllib-integration\rllib_integration\carla_core.py", line 62, in __init__
    self.init_server()
  File "D:\Projects\CARLA-RLlib\rllib-integration\rllib_integration\carla_core.py", line 85, in init_server
    "{}/CarlaUE4.sh".format(os.environ["CARLA_ROOT"]),
  File "D:\Softwares\Anaconda\anaconda3\envs\caRl\lib\os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'CARLA_ROOT'
Result for DQN_CarlaEnv_7451f_00000:
  {}

Could anyone help me with this?
Thank you.

**Comment by LucasGandara** [comment]
What python version are you using?
